on:
  workflow_dispatch:
    inputs:
      app_name:
        description: 'Build repository'
        required: true
        default: ''
      app_version:
        description: 'Build tag'
        required: true
        default: ''
      build_python:
        description: 'Build python'
        required: true
        default: '>=3.11'
      build_arch:
        description: 'Build architecture'
        required: true
        default: 'loongarch64'
      build_requires:
        description: 'Build requires'
        required: true
        default: 'curl'
  
name: cibuildwheel Custom
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        manylinux: [ manylinux_2_38 ]
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          repository: ${{ github.event.inputs.app_name }}
          ref: ${{ github.event.inputs.app_version }}

      - name: Setup QEMU
        run: docker run --rm --privileged ghcr.io/loong64/qemu-user-static --reset -p yes

      - name: Build wheels
        uses: pypa/cibuildwheel@v2.21.3
        env:
          CIBW_MANYLINUX_LOONGARCH64_IMAGE: ${{ matrix.manylinux }}
          CIBW_PROJECT_REQUIRES_PYTHON: ${{ github.event.inputs.build_python }}
          CIBW_ARCHS_LINUX: ${{ github.event.inputs.build_arch }}
          CIBW_SKIP: "*musllinux* pp*"
          CIBW_TEST_SKIP: "*"
          CIBW_BEFORE_ALL_LINUX: "curl -sSf https://sh.rustup.rs | sh -s -- -y && yum install -y ${{ github.event.inputs.build_requires }}"
          CIBW_ENVIRONMENT_LINUX: "PATH=$HOME/.cargo/bin:$PATH"

      - name: Upload wheels
        run: |
          pip install twine
          twine upload --repository-url https://gitlab.com/api/v4/projects/65746188/packages/pypi wheelhouse/*.whl
        env:
          TWINE_USERNAME: ${{ github.repository_owner }}
          TWINE_PASSWORD: ${{ secrets.GITLAB_TOKEN }}